build:
  environment:
        php: 7.4.16
  nodes:
    analysis:
      tests:
        override:
          # Add the respective Scrutinizer analysis for your language like
          - php-scrutinizer-run
